version: '2'

services:
#  spring-consul-sample:
#    build: .
#    image: spring-consul-sample
#    depends_on:
#     - consul-server
#     - consul-server2
#    stdin_open: true
#    tty: true
#    networks:
#      consul:
#        ipv4_address: 172.18.0.20
#    ports:
#     - "8080:8080"
#     - "8300:8300"
#     - "8301:8301/tcp"
#     - "8301:8301/udp"
#     - "8302:8302/tcp"
#     - "8302:8302/udp"
#     - "8400:8400"
#     - "8500:8500"
#     - "8600:8600/tcp"
#     - "8600:8600/udp"
#    environment:
#     - DC=home
#     - JOIN=10.0.99.99:32003
#     - BOOTSTRAP_EXPECT=1
#     - NODE_NAME=spring-consul-sample
#     - DELAY=10
  consul-server:
    build: ./consul-server
    image: consul-server
    stdin_open: true
    tty: true
    networks:
      consul:
        ipv4_address: 172.18.0.21
    ports:
     - "32000:32000/tcp" #DNS_PORT
     - "32000:32000/udp" #DNS_PORT
     - "32001:32001" #HTTP_PORT
     - "32002:32002" #RPC_PORT
     - "32003:32003/tcp" #SERF_LAN_PORT
     - "32003:32003/udp" #SERF_LAN_PORT
     - "32004:32004/tcp" #SERF_WAN_PORT
     - "32004:32004/udp" #SERF_WAN_PORT
     - "32005:32005" #SERVER_PORT
    environment:
     - DC=home
     - LOG_LEVEL=INFO
     - BOOTSTRAP_EXPECT=2
     - NODE_NAME=consul-server1
     - ADVERTISE=10.0.99.99
     - JOIN="10.0.99.99:32003","10.0.99.99:32013"
     - DNS_PORT=32000
     - HTTP_PORT=32001
     - RPC_PORT=32002
     - SERF_LAN_PORT=32003
     - SERF_WAN_PORT=32004
     - SERVER_PORT=32005
     - GIT_INITIAL_REPO=https://github.com/matheusgg/spring-config-repo.git
     - GIT_INITIAL_REPO_NAME=spring-config-repo
     - GIT_INITIAL_REPO_BRANCHES="master","docker"
     - GIT_POLLING_INTERVAL=1
  consul-server2:
    build: ./consul-server
    image: consul-server
    stdin_open: true
    tty: true
    networks:
      consul:
        ipv4_address: 172.18.0.22
    ports:
     - "32010:32010/tcp" #DNS_PORT
     - "32010:32010/udp" #DNS_PORT
     - "32011:32011" #HTTP_PORT
     - "32012:32012" #RPC_PORT
     - "32013:32013/tcp" #SERF_LAN_PORT
     - "32013:32013/udp" #SERF_LAN_PORT
     - "32014:32014/tcp" #SERF_WAN_PORT
     - "32014:32014/udp" #SERF_WAN_PORT
     - "32015:32015" #SERVER_PORT
    environment:
     - DC=home
     - LOG_LEVEL=INFO
     - BOOTSTRAP_EXPECT=2
     - NODE_NAME=consul-server2
     - ADVERTISE=10.0.99.99
     - JOIN="10.0.99.99:32003","10.0.99.99:32013"
     - DNS_PORT=32010
     - HTTP_PORT=32011
     - RPC_PORT=32012
     - SERF_LAN_PORT=32013
     - SERF_WAN_PORT=32014
     - SERVER_PORT=32015
     - GIT_INITIAL_REPO=https://github.com/matheusgg/spring-config-repo.git
     - GIT_INITIAL_REPO_NAME=spring-config-repo
     - GIT_INITIAL_REPO_BRANCHES="master","docker"
     - GIT_POLLING_INTERVAL=1

networks:
  consul:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16